import type { AppState } from './types';
export type NorouPermission = 'allow' | 'ask' | 'deny';
export type PermissionMap = Record<string, NorouPermission>;
const PERMISSION_KEY = 'norou_agent_permissions_v1';
const HISTORY_KEY = 'norou_agent_history_v1';
export const DEFAULT_PERMISSIONS: PermissionMap = { tasks:'allow', routines:'allow', goals:'allow', notes:'allow', calendar:'ask', alarms:'ask', memories:'ask', health:'allow', workouts:'allow', focus:'allow', destructive:'ask' };
function safeParse<T>(value: string | null, fallback: T): T { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
export function loadPermissions(): PermissionMap { if (typeof window === 'undefined') return {...DEFAULT_PERMISSIONS}; return {...DEFAULT_PERMISSIONS, ...safeParse<PermissionMap>(window.localStorage.getItem(PERMISSION_KEY), {})}; }
export function savePermissions(value: PermissionMap) { if (typeof window !== 'undefined') window.localStorage.setItem(PERMISSION_KEY, JSON.stringify(value)); }
export interface AgentHistoryEntry { id:string; at:string; command:string; summary:string; before:AppState; }
export function loadAgentHistory(): AgentHistoryEntry[] { if (typeof window === 'undefined') return []; return safeParse<AgentHistoryEntry[]>(window.localStorage.getItem(HISTORY_KEY), []).slice(0,20); }
export function saveAgentHistory(history: AgentHistoryEntry[]) { if (typeof window !== 'undefined') window.localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0,20))); }
export function categoryForAction(type:string): keyof PermissionMap { if(type.startsWith('delete_'))return'destructive'; if(type.includes('task'))return'tasks'; if(type.includes('routine'))return'routines'; if(type.includes('goal'))return'goals'; if(type.includes('note'))return'notes'; if(type.includes('event'))return'calendar'; if(type.includes('alarm'))return'alarms'; if(type.includes('memory'))return'memories'; if(type.includes('water')||type.includes('steps'))return'health'; if(type.includes('workout'))return'workouts'; if(type==='start_focus')return'focus'; return'tasks'; }
export interface AutopilotBlock { id:string; time:string; title:string; duration:number; taskId?:string; }
export function autopilotPlan(state:AppState): AutopilotBlock[] { const rank={high:0,medium:1,low:2}; const open=state.tasks.filter(t=>!t.completed).sort((a,b)=>rank[a.priority]-rank[b.priority]); const now=new Date(); const minutes=now.getHours()*60+now.getMinutes(); const start=Math.max(minutes+15,8*60); const blocks: AutopilotBlock[] = open.slice(0,4).map((task,i)=>{const begin=start+i*55;const h=Math.floor((begin%(24*60))/60).toString().padStart(2,'0');const m=(begin%60).toString().padStart(2,'0');return{id:`task-${task.id}`,time:`${h}:${m}`,title:task.title,duration:45,taskId:task.id};}); if(!blocks.length){const h=Math.floor((start%(24*60))/60).toString().padStart(2,'0');const m=(start%60).toString().padStart(2,'0');blocks.push({id:'focus',time:`${h}:${m}`,title:'Choose one important goal and start a focus session',duration:25,taskId:undefined});} return blocks; }
