/**
 * 400 original motivational lines (no real-person attributions, to avoid
 * misquoting anyone). One is picked deterministically per calendar day so
 * it's stable all day and repeats roughly once per year.
 */
export const QUOTES: string[] = [
  "Discipline doesn't care how you feel this morning.",
  "You're not behind. You're exactly where consistent effort puts you next.",
  "Focus doesn't ask how you feel today.",
  "Intention doesn't care how you feel this morning.",
  "Nobody is coming to save you from your own routine. Good — you don't need saving.",
  "Progress isn't owed to you. It's earned in ordinary, unremarkable repetitions.",
  "You don't find intention. You practice it.",
  "Trust momentum, not your mood.",
  "Habits compound quietly until they don't.",
  "Resilience beats motivation every single time.",
  "Structure is the quiet engine behind every visible result.",
  "A goal without a routine is just a wish with a deadline.",
  "Discipline built today is the only kind that counts.",
  "You don't find progress. You practice it.",
  "Energy follows action, not the other way around.",
  "Focus compounds quietly until it doesn't.",
  "Resilience shows up even when inspiration doesn't.",
  "Resilience is the whole strategy.",
  "Momentum is a decision you make again, not once.",
  "Every master was once a beginner who refused to quit.",
  "Structure beats motivation every single time.",
  "Structure outlasts every excuse you can think of.",
  "Commitment built today is the only kind that counts.",
  "Practice doesn't care how you feel this morning.",
  "There is no finish line, only a next rep.",
  "Small choices are boring. That's exactly why they work.",
  "Good habits are the quiet engine behind every visible result.",
  "Progress outlasts every excuse you can think of.",
  "Momentum beats motivation every single time.",
  "Practice is boring. That's exactly why it works.",
  "Tiny wins show up even when inspiration doesn't.",
  "Willpower built today is the only kind that counts.",
  "Patience is a decision you make again, not once.",
  "Willpower is what happens after the excuse runs out.",
  "Whatever you do today, do it like it's the rep that decides the streak.",
  "Growth is the quiet engine behind every visible result.",
  "Habits beat motivation every single time.",
  "You don't have to be extreme, just consistent.",
  "Habits are decisions you make again, not once.",
  "Resilience compounds quietly until it doesn't.",
  "Patience doesn't care how you feel this morning.",
  "You don't find repetition. You practice it.",
  "Bet on effort. It never no-shows.",
  "Momentum compounds quietly until it doesn't.",
  "Progress beats motivation every single time.",
  "Routine is a decision you make again, not once.",
  "Bet on intention. It never no-shows.",
  "You don't need to feel it to do it.",
  "You don't find practice. You practice it.",
  "Bet on patience. It never no-shows.",
  "Daily reps are a muscle. Use them or lose them.",
  "Focus shows up even when inspiration doesn't.",
  "Your streak isn't the point. Who it's turning you into is the point.",
  "Trust willpower, not your mood.",
  "The bar you keep clearing was once the bar you couldn't imagine reaching.",
  "Discipline is what happens after the excuse runs out.",
  "Winners quit less often than losers, not less often than failure happens.",
  "Quiet mornings outlast every excuse you can think of.",
  "Discipline is the whole strategy.",
  "Progress is the quiet engine behind every visible result.",
  "Persistence doesn't care how you feel this morning.",
  "Effort shows up even when inspiration doesn't.",
  "Follow-through is a decision you make again, not once.",
  "Routine beats motivation every single time.",
  "Your goals don't care about your excuses, and neither should you.",
  "Bet on discipline. It never no-shows.",
  "Habits are the whole strategy.",
  "Resilience doesn't ask how you feel today.",
  "Momentum doesn't ask how you feel today.",
  "You don't find willpower. You practice it.",
  "You don't need permission to start over today.",
  "Bet on persistence. It never no-shows.",
  "Practice is the quiet engine behind every visible result.",
  "Small steps don't ask how you feel today.",
  "One percent better today is unrecognizable a year from now.",
  "Follow-through doesn't care how you feel this morning.",
  "You don't have to win today. You just have to not quit today.",
  "You don't need a new plan. You need to run the one you have.",
  "Every streak was once just a single day that didn't break.",
  "Slow progress is still progress. Stopped progress is not.",
  "You are always either building the habit or building the excuse.",
  "Habits outlast every excuse you can think of.",
  "Effort doesn't care how you feel this morning.",
  "Effort is the one variable that's always fully within your control.",
  "You can't out-motivate a bad routine. Fix the routine.",
  "Daily reps outlast every excuse you can think of.",
  "Tiny wins don't care how you feel this morning.",
  "Effort is a decision you make again, not once.",
  "Discipline is remembering what you wanted before you got distracted.",
  "Good habits don't care how you feel this morning.",
  "Repetition shows up even when inspiration doesn't.",
  "Bet on consistency. It never no-shows.",
  "Tiny wins built today are the only kind that count.",
  "The best time to start was earlier. The next best time is right now.",
  "Patience is the quiet engine behind every visible result.",
  "Some days you show up for results. Other days you show up for proof you still can.",
  "Bet on follow-through. It never no-shows.",
  "The version of you that quits today is not the version you're building.",
  "Good habits outlast every excuse you can think of.",
  "Your future is being built right now, in this unremarkable moment.",
  "You don't find effort. You practice it.",
  "Track it, and it improves. Ignore it, and it doesn't.",
  "Follow-through is boring. That's exactly why it works.",
  "Practice doesn't ask how you feel today.",
  "Intention beats motivation every single time.",
  "Effort is the whole strategy.",
  "Good habits are boring. That's exactly why they work.",
  "You are the sum of what you do when nobody's grading you.",
  "Difficult roads often lead to destinations worth reaching.",
  "Future you is watching. Don't embarrass them.",
  "Do it scared. Do it tired. Just do it.",
  "Small choices compound quietly until they don't.",
  "Good habits built today are the only kind that count.",
  "Show up for the version of you that's still deciding whether to believe in this.",
  "Persistence beats motivation every single time.",
  "Today is a rough draft. Make it a good one anyway.",
  "Discipline is the quiet engine behind every visible result.",
  "Tiny wins outlast every excuse you can think of.",
  "Bet on practice. It never no-shows.",
  "Practice outlasts every excuse you can think of.",
  "You don't have to feel ready. You just have to start.",
  "Habits built today are the only kind that count.",
  "Small steps show up even when inspiration doesn't.",
  "What you repeat, you become.",
  "Quiet mornings built today are the only kind that count.",
  "Persistence outlasts every excuse you can think of.",
  "Intention compounds quietly until it doesn't.",
  "Excellence is just a habit wearing a fancy name tag.",
  "A single good decision can end a week-long slump.",
  "Habits are a muscle. Use them or lose them.",
  "Follow-through outlasts every excuse you can think of.",
  "Show up ugly. Showing up beautifully can wait for day 100.",
  "Perfection is the enemy of the streak. Keep the streak.",
  "Ordinary days beat motivation every single time.",
  "Focus doesn't care how you feel this morning.",
  "Routine is the whole strategy.",
  "Bet on momentum. It never no-shows.",
  "Growth compounds quietly until it doesn't.",
  "Every level was built one unglamorous rep at a time.",
  "Nobody remembers the day you started. Everybody notices the day you quit.",
  "The comeback is always stronger than the setback — if you let it be.",
  "Patience beats motivation every single time.",
  "Patience outlasts every excuse you can think of.",
  "Resilience outlasts every excuse you can think of.",
  "Small steps are a muscle. Use them or lose them.",
  "Resilience doesn't care how you feel this morning.",
  "Intention is the quiet engine behind every visible result.",
  "Consistency turns 'I hope' into 'I know'.",
  "Tiny wins compound quietly until they don't.",
  "Small choices don't ask how you feel today.",
  "Structure is the whole strategy.",
  "Routine built today is the only kind that counts.",
  "Progress hides in the sessions nobody applauds.",
  "A rough day doesn't erase a good streak — it tests it.",
  "A single rep won't transform you, but a thousand of them will.",
  "Structure doesn't ask how you feel today.",
  "Willpower is boring. That's exactly why it works.",
  "Good habits are a muscle. Use them or lose them.",
  "The floor of a bad day is still higher than the ceiling of doing nothing.",
  "Systems outlast motivation. Build the system.",
  "Focus is the quiet engine behind every visible result.",
  "Practice compounds quietly until it doesn't.",
  "Intention outlasts every excuse you can think of.",
  "The workout you almost skipped is usually the one that mattered most.",
  "Routine is a muscle. Use it or lose it.",
  "Good habits show up even when inspiration doesn't.",
  "Commitment outlasts every excuse you can think of.",
  "Trust progress, not your mood.",
  "Trust routine, not your mood.",
  "Progress built today is the only kind that counts.",
  "Consistency beats motivation every single time.",
  "Repetition is what happens after the excuse runs out.",
  "Ordinary days outlast every excuse you can think of.",
  "Routine is boring. That's exactly why it works.",
  "Effort is what happens after the excuse runs out.",
  "Bet on routine. It never no-shows.",
  "Small choices built today are the only kind that count.",
  "Patience is the whole strategy.",
  "Small steps are boring. That's exactly why they work.",
  "Consistency is a decision you make again, not once.",
  "Ordinary days don't care how you feel this morning.",
  "Small choices are a muscle. Use them or lose them.",
  "Effort is the quiet engine behind every visible result.",
  "Small steps are decisions you make again, not once.",
  "Habits are the quiet engine behind every visible result.",
  "Bet on resilience. It never no-shows.",
  "Today's effort is a letter to tomorrow's confidence.",
  "Patience built today is the only kind that counts.",
  "Habits are boring. That's exactly why they work.",
  "Focus is the whole strategy.",
  "Trust resilience, not your mood.",
  "Resilience built today is the only kind that counts.",
  "Tiny wins beat motivation every single time.",
  "You don't find resilience. You practice it.",
  "Practice shows up even when inspiration doesn't.",
  "Tiny wins are decisions you make again, not once.",
  "Consistency is what happens after the excuse runs out.",
  "Not motivated today? Show up anyway. Motivation will catch up.",
  "Small steps are the quiet engine behind every visible result.",
  "Quiet mornings don't care how you feel this morning.",
  "You are always one small decision from a completely different day.",
  "The grind doesn't care about your feelings. Neither does your future.",
  "Repetition is boring. That's exactly why it works.",
  "Done is better than perfect, and perfect rarely ships anyway.",
  "Practice is a decision you make again, not once.",
  "You don't find growth. You practice it.",
  "Don't wait for Monday. Monday isn't coming to save you either.",
  "Growth built today is the only kind that counts.",
  "Progress is what happens after the excuse runs out.",
  "Trust structure, not your mood.",
  "Routine doesn't care how you feel this morning.",
  "Focus is boring. That's exactly why it works.",
  "Discipline doesn't ask how you feel today.",
  "Your habits are quietly writing a résumé for the person you're becoming.",
  "The gym doesn't care that you're tired. Neither does your goal.",
  "Bet on commitment. It never no-shows.",
  "Your only competition is who you were yesterday.",
  "Persistence doesn't ask how you feel today.",
  "Start before you're ready. Ready is a myth anyway.",
  "Progress doesn't ask how you feel today.",
  "The only workout you regret is the one you skipped.",
  "Daily reps are the quiet engine behind every visible result.",
  "You're not too far gone. You're one good day away from a good week.",
  "Resilience is the quiet engine behind every visible result.",
  "Effort outlasts every excuse you can think of.",
  "Nobody levels up by accident.",
  "Daily reps built today are the only kind that count.",
  "Momentum shows up even when inspiration doesn't.",
  "What feels hard today is what feels normal in a month.",
  "Trust intention, not your mood.",
  "Setbacks are data, not verdicts.",
  "Repetition is the whole strategy.",
  "Motivation gets you started. Identity keeps you going.",
  "Growth doesn't ask how you feel today.",
  "Persistence built today is the only kind that counts.",
  "Growth is the whole strategy.",
  "The pain of discipline weighs ounces. The pain of regret weighs tons.",
  "Follow-through compounds quietly until it doesn't.",
  "Momentum is a muscle. Use it or lose it.",
  "Structure is boring. That's exactly why it works.",
  "Follow-through is what happens after the excuse runs out.",
  "Daily reps are decisions you make again, not once.",
  "Small wins, stacked daily, are how empires and abs get built.",
  "Effort built today is the only kind that counts.",
  "Routine is what happens after the excuse runs out.",
  "Trust discipline, not your mood.",
  "You don't find focus. You practice it.",
  "Follow-through is a muscle. Use it or lose it.",
  "Willpower doesn't care how you feel this morning.",
  "Ordinary days are decisions you make again, not once.",
  "Half-effort still beats zero effort — but full effort compounds faster.",
  "You are one decision away from a completely different trajectory.",
  "Ordinary days compound quietly until they don't.",
  "Growth outlasts every excuse you can think of.",
  "The habit you're building right now is quietly building you back.",
  "Great habits are built in average moments, not extraordinary ones.",
  "Quiet mornings are decisions you make again, not once.",
  "Discipline is a muscle. Use it or lose it.",
  "Trust consistency, not your mood.",
  "Trust practice, not your mood.",
  "Structure built today is the only kind that counts.",
  "Discipline outlasts every excuse you can think of.",
  "Progress doesn't care how you feel this morning.",
  "Follow-through is the whole strategy.",
  "The only bad workout is the one that didn't happen.",
  "Resilience is boring. That's exactly why it works.",
  "Willpower outlasts every excuse you can think of.",
  "Consistency doesn't ask how you feel today.",
  "Growth is a muscle. Use it or lose it.",
  "Persistence is boring. That's exactly why it works.",
  "Persistence is a decision you make again, not once.",
  "Trust focus, not your mood.",
  "Persistence is the whole strategy.",
  "Small steps are the whole strategy.",
  "Daily reps compound quietly until they don't.",
  "Structure is a muscle. Use it or lose it.",
  "Quiet mornings are the quiet engine behind every visible result.",
  "Small steps outlast every excuse you can think of.",
  "Follow-through doesn't ask how you feel today.",
  "Discipline is boring. That's exactly why it works.",
  "Intention shows up even when inspiration doesn't.",
  "Stop waiting for the version of you that feels like doing this. Build it instead.",
  "Commitment is the whole strategy.",
  "Bet on growth. It never no-shows.",
  "Intention is a muscle. Use it or lose it.",
  "Consistency isn't glamorous. Neither are most things worth having.",
  "You're not chasing perfect. You're chasing better than yesterday.",
  "Whatever you're avoiding today is usually exactly what you need to do today.",
  "A body in motion stays in motion. Get moving.",
  "Willpower compounds quietly until it doesn't.",
  "Comfort is expensive. It costs you the person you could've been.",
  "The best routines are the ones boring enough to survive a bad mood.",
  "Daily reps are boring. That's exactly why they work.",
  "Discipline shows up even when inspiration doesn't.",
  "Ordinary days show up even when inspiration doesn't.",
  "Every champion was once someone who just didn't stop.",
  "Commitment is boring. That's exactly why it works.",
  "Effort is boring. That's exactly why it works.",
  "Structure compounds quietly until it doesn't.",
  "Small choices are the whole strategy.",
  "Persistence is a muscle. Use it or lose it.",
  "Consistency shows up even when inspiration doesn't.",
  "Momentum is just discipline with a head start.",
  "Momentum is what happens after the excuse runs out.",
  "Small choices outlast every excuse you can think of.",
  "Small choices don't care how you feel this morning.",
  "Willpower is a muscle. Use it or lose it.",
  "Structure is what happens after the excuse runs out.",
  "Commitment beats motivation every single time.",
  "Practice is what happens after the excuse runs out.",
  "Daily reps don't care how you feel this morning.",
  "Growth is what happens after the excuse runs out.",
  "You don't find momentum. You practice it.",
  "The best apology to your past mistakes is different behavior.",
  "Intention is the whole strategy.",
  "Progress is a muscle. Use it or lose it.",
  "You don't find patience. You practice it.",
  "Discipline is a form of self-respect you practice daily.",
  "A rep you don't want to do is worth more than the one you do.",
  "Good habits are the whole strategy.",
  "Follow-through is the quiet engine behind every visible result.",
  "Effort doesn't ask how you feel today.",
  "Repetition is the quiet engine behind every visible result.",
  "Persistence is the quiet engine behind every visible result.",
  "Be the person your future self is grateful you didn't quit on.",
  "Focus is a muscle. Use it or lose it.",
  "Streaks aren't about perfection. They're about refusing to quit twice in a row.",
  "Routine outlasts every excuse you can think of.",
  "Effort beats motivation every single time.",
  "Consistency compounds quietly until it doesn't.",
  "The hardest part is starting. The second hardest part is not stopping.",
  "Focus is a decision you make again, not once.",
  "Momentum built today is the only kind that counts.",
  "Intention doesn't ask how you feel today.",
  "Nothing changes if nothing changes — so change one thing today.",
  "Small choices are decisions you make again, not once.",
  "Structure doesn't care how you feel this morning.",
  "Ordinary days built today are the only kind that count.",
  "Discipline compounds quietly until it doesn't.",
  "Good habits are decisions you make again, not once.",
  "Quiet mornings are a muscle. Use them or lose them.",
  "Momentum outlasts every excuse you can think of.",
  "Tiny wins are boring. That's exactly why they work.",
  "Discomfort today is just tuition for the person you're becoming.",
  "Tiny wins don't ask how you feel today.",
  "Structure shows up even when inspiration doesn't.",
  "Momentum is boring. That's exactly why it works.",
  "You can't save time. You can only spend it on purpose.",
  "Follow-through beats motivation every single time.",
  "Daily reps show up even when inspiration doesn't.",
  "Tiny wins are a muscle. Use them or lose them.",
  "Everything worth having was built in the boring middle, not the exciting start.",
  "Trust repetition, not your mood.",
  "Persistence shows up even when inspiration doesn't.",
  "Daily reps are the whole strategy.",
  "Resilience is a muscle. Use it or lose it.",
  "Do it now — later has a way of turning into never.",
  "Intention built today is the only kind that counts.",
  "Patience is what happens after the excuse runs out.",
  "Bet on focus. It never no-shows.",
  "Habits show up even when inspiration doesn't.",
  "The gap between who you are and who you want to be is called discipline.",
  "Momentum doesn't care how you feel this morning.",
  "Good habits beat motivation every single time.",
  "Patience compounds quietly until it doesn't.",
  "Trust patience, not your mood.",
  "You don't find consistency. You practice it.",
  "Routine shows up even when inspiration doesn't.",
  "Growth is a decision you make again, not once.",
  "Small steps don't care how you feel this morning.",
  "You don't find discipline. You practice it.",
  "Commitment is a muscle. Use it or lose it.",
  "Small choices are the quiet engine behind every visible result.",
  "Small steps built today are the only kind that count.",
  "Persistence compounds quietly until it doesn't.",
  "Follow-through shows up even when inspiration doesn't.",
  "Consistency is boring. That's exactly why it works.",
  "You don't find routine. You practice it.",
  "Patience is boring. That's exactly why it works.",
  "Repetition doesn't ask how you feel today.",
  "Trust persistence, not your mood.",
  "Repetition outlasts every excuse you can think of.",
  "Hard choices, easy life. Easy choices, hard life.",
  "Small steps beat motivation every single time.",
  "Habits don't ask how you feel today.",
  "Trust follow-through, not your mood.",
  "Repetition beats motivation every single time.",
  "You are not too old, too late, or too far behind to start again today.",
  "Commitment shows up even when inspiration doesn't.",
  "Small choices beat motivation every single time.",
  "Bet on repetition. It never no-shows.",
  "Ordinary days are boring. That's exactly why they work.",
  "Persistence is what happens after the excuse runs out.",
  "Your habits are voting for the person you're becoming, one ballot at a time.",
  "Tiny wins are the quiet engine behind every visible result.",
  "The days you don't feel like it are the days that count the most.",
  "Discomfort is feedback that you're actually growing.",
  "Willpower shows up even when inspiration doesn't.",
  "Practice is the whole strategy.",
  "Willpower is the whole strategy.",
];

/** Deterministic day-of-year index into QUOTES, stable for the whole day. */
export function quoteForDate(date: Date = new Date()): string {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / 86_400_000);
  return QUOTES[dayOfYear % QUOTES.length];
}
