/**
 * 400 original daily lessons inspired by the themes of the user's selected books.
 * These are original lines, not copied passages or attributed quotations.
 * One is picked deterministically per calendar day so it stays stable all day.
 */
export const QUOTES: string[] = [
  'Wealth grows when your choices leave room for tomorrow.',
  'What you keep matters as much as what you earn.',
  'A calm financial life is built more by habits than by headlines.',
  'Knowing what is enough protects you from chasing what never satisfies.',
  'Long-term thinking turns ordinary decisions into powerful ones.',
  'Freedom is often the ability to choose your time, not just your purchases.',
  'Good money decisions leave you with options when life changes.',
  'Your future self is one of the most important people your money can serve.',
  'Patience is a financial advantage because time gives good decisions room to work.',
  'Not every opportunity deserves your money, attention, or risk.',
  'Comparison can make a perfectly good life feel insufficient.',
  'A bigger number is not automatically a better life.',
  'Keeping a margin for surprises is a form of strength.',
  'Your behaviour with money matters more than your ability to predict markets.',
  'Being able to wait is a powerful form of financial discipline.',
  'Quiet consistency can beat dramatic financial decisions over time.',
  'Protecting what you have can be as valuable as chasing more.',
  'Every purchase trades money for something; know what you are actually buying.',
  'Risk becomes easier to handle when you leave yourself room for error.',
  'Your goals should decide your spending, not someone else’s lifestyle.',
  'Luck and uncertainty are always part of outcomes, so stay humble about both.',
  'A strong plan includes what you will do when the plan goes wrong.',
  'Financial independence is built from repeated choices, not one perfect move.',
  'If you cannot explain why you want something, pause before paying for it.',
  'Patience turns time from an enemy into an ally.',
  'Your savings buy future choices before they buy future things.',
  'Protecting your peace can be a better return than impressing other people.',
  'Good financial habits should survive a bad month.',
  'You do not need to win every opportunity; you need to avoid ruining your future.',
  'Consistency makes small financial advantages compound.',
  'The best plan is one you can actually keep following.',
  'Enough is a boundary that protects you from endless comparison.',
  'Uncertainty is easier to face when your lifestyle has breathing room.',
  'Use money to support your values rather than manufacture an image.',
  'Future freedom often begins with present restraint.',
  'Financial progress can look boring while it is working.',
  'Avoiding a terrible decision can matter more than finding a brilliant one.',
  'Your money habits reveal what you repeatedly prioritise.',
  'Build a life that does not require every month to go perfectly.',
  'Let time and consistency do more of the heavy lifting than impulse.',
  'The smallest useful action is still a vote for the person you want to become.',
  'Change your routine before demanding a different result.',
  'Make good actions easier to start and bad actions harder to repeat.',
  'A habit becomes powerful when it stops requiring a daily debate.',
  'Your environment quietly teaches you what to do next.',
  'Consistency is built from returning after imperfect days.',
  'Focus on the next repeatable action, not the entire mountain.',
  'A tiny improvement becomes meaningful when you give it enough time.',
  'Identity grows from evidence, and your actions provide that evidence.',
  'Build routines that make progress feel normal.',
  'If a habit is too hard to start, make the first step smaller.',
  'Never underestimate the power of removing one unnecessary obstacle.',
  'Repetition makes effort cheaper over time.',
  'Your calendar is a map of the behaviours you are actually practising.',
  'Create a clear cue for the action you want to remember.',
  'Pairing a new habit with an existing routine can make it easier to repeat.',
  'Missing once is a moment; abandoning the routine is a decision.',
  'Good systems reduce how much you need to rely on motivation.',
  'Celebrate showing up, because showing up creates the pattern.',
  'Your habits shape your default response when motivation disappears.',
  'Progress is often invisible before it becomes obvious.',
  'A better routine can make a difficult goal feel ordinary.',
  'Choose habits that fit the life you actually live.',
  'Every repetition strengthens a pathway you may rely on later.',
  'Lower the starting friction until beginning feels almost automatic.',
  'Protect the first minute of a habit; it often determines the next thirty.',
  'You can redesign a routine without redesigning your entire life.',
  'Small wins become a system when you repeat them on purpose.',
  'Your future behaviour is being rehearsed by what you do today.',
  'Good habits are easier to keep when their rewards are visible.',
  'Do not wait to feel like the person you want to become; act like them in small ways.',
  'One useful repeat today is more valuable than ten perfect plans for tomorrow.',
  'When a habit fails, fix the system before blaming yourself.',
  'Consistency does not mean perfection; it means returning.',
  'The routine you can sustain beats the routine you can only admire.',
  'Your surroundings can either support your goals or constantly negotiate against them.',
  'Make the desired action obvious enough that you cannot easily forget it.',
  'Progress compounds when you keep giving the same small behaviour another chance.',
  'Every day offers another repetition of the identity you are building.',
  'Build a system that makes the right thing easier on your tired days.',
  'You do not need universal approval to live according to your values.',
  'Another person’s opinion is information, not a command.',
  'Your task is to control your choices, not manage every reaction around you.',
  'Freedom grows when you stop outsourcing your worth to other people.',
  'You can respect someone without taking responsibility for their entire life.',
  'Comparison often turns someone else’s path into a cage for your own.',
  'Choose your direction before asking whether everyone will understand it.',
  'Past experiences can explain you without having to permanently define you.',
  'Approval is a pleasant bonus, not a requirement for a meaningful life.',
  'Healthy boundaries let people own their choices without constant conflict.',
  'You cannot build your identity entirely from other people’s expectations.',
  'Let disagreement exist without making it a crisis.',
  'Your value does not increase every time someone praises you.',
  'You can change your future without waiting for your past to become perfect.',
  'Being misunderstood is sometimes the price of choosing your own path.',
  'Focus on the contribution you can make rather than the applause it receives.',
  'Not every criticism deserves a change in direction.',
  'You can listen carefully without surrendering your judgement.',
  'Other people have their own tasks, fears, goals, and choices.',
  'Peace often begins when you stop trying to control every outcome.',
  'Your life becomes clearer when you separate your responsibilities from everyone else’s.',
  'You are allowed to choose what matters to you.',
  'Confidence can mean acting without needing certainty about everyone’s opinion.',
  'Comparison hides the fact that different people are solving different problems.',
  'Freedom includes the courage to disappoint expectations that are not yours.',
  'You can care about people without living for their approval.',
  'A difficult conversation does not automatically mean you made the wrong choice.',
  'Your next action matters more than endlessly explaining your last one.',
  'Let your values provide the direction when praise and criticism pull in opposite ways.',
  'You do not need to win every social interaction to have a good life.',
  'Accepting limits can free energy for the things you can actually change.',
  'You are responsible for your choices even when circumstances are not your fault.',
  'Other people’s freedom includes their freedom to disagree with you.',
  'Your worth is not a group project.',
  'Build a life you can respect even when nobody is watching.',
  'Approval can disappear overnight; values can guide you for years.',
  'When you stop performing for everyone, you have more energy to live deliberately.',
  'Your path does not become wrong simply because it is different.',
  'Choose responsibility over blame when deciding what to do next.',
  'You can be kind without becoming controlled by other people’s expectations.',
  'A thought can be loud without being true.',
  'Pause before treating every mental story as a fact.',
  'Not every worry deserves a prediction.',
  'You can notice a thought without obeying it.',
  'Clarity often arrives after you stop arguing with every thought.',
  'An anxious possibility is not the same thing as a certain outcome.',
  'Give yourself a moment between a thought and your response.',
  'Your mind can generate stories faster than reality can confirm them.',
  'Question the interpretation before condemning the situation.',
  'Peace can begin with refusing to rehearse an imagined disaster.',
  'You are allowed to change your mind when better information arrives.',
  'One difficult moment does not prove that the whole future will be difficult.',
  'Feelings deserve attention without automatically becoming instructions.',
  'Look for what is happening now, not only what your mind predicts next.',
  'An uncomfortable thought can pass without becoming a permanent belief.',
  'You do not have to solve every thought the moment it appears.',
  'Curiosity is often more useful than self-criticism.',
  'Before believing a harsh conclusion, ask what evidence supports it.',
  'Your first interpretation is not always your best interpretation.',
  'Create space for uncertainty instead of filling it with fear.',
  'A thought can be familiar and still be unhelpful.',
  'You can observe your mind without turning observation into judgement.',
  'Calm attention gives you more choices than automatic reaction.',
  'When your mind says always, never, or everyone, check the facts.',
  'You are more than the story your mind tells about one mistake.',
  'Let facts have a vote before assumptions make the final decision.',
  'An emotion can be real without its explanation being correct.',
  'Your attention is valuable; do not spend it on every mental notification.',
  'Sometimes the strongest response is simply not feeding the thought.',
  'You can return to the present even after your mind wanders into the future.',
  'Fear often asks for certainty that life cannot provide.',
  'Replace automatic conclusions with useful questions.',
  'You do not need to believe every sentence your mind produces.',
  'Give difficult thoughts less authority and more observation.',
  'Your mind is a tool; it does not need to be your commander.',
  'When a thought repeats, investigate it instead of assuming repetition makes it true.',
  'Clarity grows when you stop treating imagination as evidence.',
  'You can make a good decision without feeling completely certain.',
  'Notice the thought, check the facts, then choose your response.',
  'Peace is easier to protect when you stop turning every possibility into a prophecy.',
  'Let people reveal their choices without trying to manage every one of them.',
  'Your energy is limited; spend more of it on what you can influence.',
  'You cannot force someone to understand what they are not ready to understand.',
  'Boundaries become clearer when you stop confusing control with care.',
  'Let someone have their opinion while you keep your own direction.',
  'Not every behaviour needs a reaction from you.',
  'Protect your peace by choosing where your attention goes.',
  'You can step back without giving up your standards.',
  'People show you a lot when you stop trying to script their behaviour.',
  'Your response is one of the few parts of a conflict you can fully own.',
  'Let consequences teach where arguments cannot.',
  'You do not have to chase people into giving you the treatment you need.',
  'Give others room to choose, then decide what their choices mean for you.',
  'Your boundary is about what you will do, not how you will control someone else.',
  'Sometimes stepping back gives you more information than pushing harder.',
  'You can care deeply without taking over another person’s responsibilities.',
  'When someone chooses distance, respect the information in that choice.',
  'Let go of the need to win every misunderstanding.',
  'Focus on your standards instead of constantly monitoring someone else’s behaviour.',
  'Not every silence needs to be filled.',
  'You cannot make someone value what you value.',
  'Peace often requires accepting that other people have their own agendas.',
  'Choose your next move from your values, not from someone else’s reaction.',
  'You can leave room for people to surprise you instead of predicting them constantly.',
  'Let people make their choices; let yourself make yours.',
  'Control feels powerful until it becomes exhausting.',
  'You do not need permission to protect your time and attention.',
  'When you stop chasing approval, you can notice who meets you willingly.',
  'Acceptance is not agreement; it is recognising what is outside your control.',
  'Use your energy to build your life rather than police someone else’s.',
  'A boundary can be quiet and still be firm.',
  'You can hear criticism without handing it the steering wheel.',
  'Give people the freedom to be themselves, then choose your response wisely.',
  'Not every relationship problem can be solved by trying harder.',
  'Your peace is partly shaped by what you repeatedly choose to engage with.',
  'Let reality speak before you spend energy trying to negotiate it away.',
  'You can stop chasing and start observing.',
  'When you release control, you often see choices more clearly.',
  'Protect your attention like a resource, because it is one.',
  'Choose influence over control wherever possible.',
  'Presence becomes more powerful when you stop trying to impress everyone.',
  'Listen closely; people reveal themselves through what they value.',
  'Attention is meaningful when it is genuine rather than performative.',
  'Confidence is quieter when it does not need constant proof.',
  'Curiosity creates better conversations than trying to dominate them.',
  'Give people space to speak and you may learn what actually matters to them.',
  'Charisma begins with making other people feel seen, not with pretending to be perfect.',
  'Mystery is often just the discipline of not oversharing everything immediately.',
  'Your manner can influence a room before your words do.',
  'Good social instincts start with observation.',
  'Respect makes influence more sustainable than pressure.',
  'People remember how comfortable they felt around you.',
  'Being interesting starts with being interested.',
  'Confidence and arrogance differ in how much space they leave for others.',
  'Choose your words with intention rather than filling every silence.',
  'Warmth can be more memorable than trying to appear impressive.',
  'Pay attention to context; the same approach does not work everywhere.',
  'Influence grows when people feel they still have a choice.',
  'Your reputation is built from repeated interactions, not one performance.',
  'Presence means giving the moment enough attention to notice what is actually happening.',
  'Good conversation is an exchange, not a competition for airtime.',
  'Learn what motivates people without reducing them to a strategy.',
  'Emotional awareness can make your communication more precise.',
  'Confidence leaves room for curiosity because it does not fear not knowing.',
  'People are more open when they feel respected rather than managed.',
  'Your strongest social skill may be knowing when not to speak.',
  'Attention without respect becomes manipulation; choose the respectful path.',
  'Influence is healthier when it preserves the other person’s freedom.',
  'Listen for the meaning behind the words, not just the words themselves.',
  'Your energy changes a conversation before your argument does.',
  'Good timing can matter as much as good wording.',
  'Be memorable by being genuinely present, not artificially mysterious.',
  'Observe first, respond second.',
  'People notice consistency between your words and your behaviour.',
  'Confidence grows when you can handle a conversation without controlling it.',
  'Ask better questions and you will often receive better information.',
  'Connection becomes easier when you stop performing a character.',
  'Influence without trust is fragile.',
  'Your social presence improves when your attention is deliberate.',
  'Respect is the foundation beneath any influence worth keeping.',
  'Mastery is built through deliberate practice long after novelty disappears.',
  'Choose a skill worth staying with when progress becomes slow.',
  'Experts become reliable by studying details beginners overlook.',
  'Practice should reveal what to improve next, not just prove what you can already do.',
  'Patience matters because deep skill takes longer than motivation lasts.',
  'Use mistakes as information instead of evidence that you should quit.',
  'Your attention is the raw material of mastery.',
  'Good mentors can shorten the distance between effort and understanding.',
  'Learn the fundamentals until they become dependable under pressure.',
  'Curiosity keeps practice alive when applause disappears.',
  'Be willing to be bad at something long enough to become better.',
  'Progress accelerates when you can identify the exact weakness you need to train.',
  'Deep work requires protecting time from unnecessary interruption.',
  'Mastery is less about intensity once and more about quality repeated.',
  'Learn from people who have already solved the problems you are facing.',
  'Your first version should teach you what the second version needs.',
  'Observe your own performance like a student, not a judge.',
  'Complex skills are built from simple pieces connected well.',
  'Choose depth when constant novelty keeps you shallow.',
  'Your craft improves when feedback becomes part of the routine.',
  'Knowledge becomes useful when you can apply it under real conditions.',
  'Repetition without attention can preserve mistakes, so practise deliberately.',
  'Build a strong foundation before chasing advanced tricks.',
  'Focus on becoming capable, not merely looking talented.',
  'Every difficult skill has a period where progress feels invisible.',
  'Your standards can rise without turning practice into self-punishment.',
  'Long projects reward people who can keep learning after the excitement fades.',
  'Learn the rules well enough to know when a different approach is useful.',
  'Protect your curiosity from the pressure to know everything immediately.',
  'Your environment should make serious practice easier to begin.',
  'Competence grows when you repeatedly solve slightly harder problems.',
  'Good practice is specific enough to tell you what changed.',
  'If you want unusual results, become unusually patient with the learning process.',
  'Your craft deserves attention even when nobody is watching.',
  'Feedback is valuable when you use it to adjust rather than defend.',
  'Build range through exploration, then build depth through commitment.',
  'Consistency gives talent enough time to become dependable skill.',
  'The boring fundamentals are often carrying the impressive results.',
  'Learn from failure without making failure your identity.',
  'Mastery is a direction you keep choosing, not a finish line you finally reach.',
  'Observe the room before deciding how you want to act in it.',
  'Protect your reputation through consistent behaviour, not constant explanation.',
  'Information becomes useful when you know when and how to share it.',
  'Choose your commitments carefully because every commitment uses future freedom.',
  'Emotional reactions can reveal more than deliberate words, so pause before responding.',
  'Not every disagreement needs to become a public contest.',
  'Build competence so your position does not depend entirely on persuasion.',
  'Know what outcome you actually want before choosing a tactic.',
  'People remember patterns, so let your actions create the reputation you want.',
  'Keep your goals clear even when the social environment is noisy.',
  'Influence is easier to sustain when people trust your reliability.',
  'Before challenging a system, understand how it works.',
  'Choose battles that matter rather than proving yourself in every moment.',
  'Your attention is a strategic resource; spend it deliberately.',
  'Listen for incentives because behaviour often follows what people value.',
  'Be careful with promises made for short-term approval.',
  'Position matters, but preparation gives position substance.',
  'You can be firm without making every interaction adversarial.',
  'Learn to recognise when patience creates a better opening than force.',
  'Protect your credibility by matching confidence to evidence.',
  'Do not let pride turn a small disagreement into a costly one.',
  'Good strategy considers what happens after the immediate win.',
  'Keep your options open when the situation is uncertain.',
  'Observe who influences decisions, not only who speaks the loudest.',
  'Use discretion when sharing plans that are still unfinished.',
  'Your strongest position is often having alternatives.',
  'Calmness can prevent someone else’s urgency from becoming your mistake.',
  'Influence grows when your actions remain predictable in the ways that matter.',
  'If you want cooperation, understand what the other person needs as well as what you need.',
  'Reputation compounds from small interactions that most people forget.',
  'Know the difference between appearing powerful and being capable.',
  'Good strategy includes knowing when to walk away.',
  'You do not need to answer every provocation.',
  'Protect your long-term interests from short-term ego.',
  'When stakes are high, slow down enough to separate facts from emotion.',
  'Preparation creates choices when pressure arrives.',
  'Influence without trust creates resistance eventually.',
  'Use social awareness to avoid unnecessary conflict, not to manufacture it.',
  'Keep perspective when a temporary setback feels personal.',
  'Your best strategic advantage is often understanding the situation clearly.',
  'People often protect their self-image before they protect the truth.',
  'Watch repeated behaviour; it usually tells you more than isolated words.',
  'Your own emotions can distort your reading of another person.',
  'Pause before assuming you know someone’s motives.',
  'Everyone has blind spots, including you.',
  'Understanding a pattern does not require excusing harmful behaviour.',
  'Jealousy often says more about comparison than about the person being watched.',
  'Pride can make small mistakes expensive when nobody wants to admit them.',
  'People respond differently under pressure, so context matters.',
  'Listen for what someone avoids as well as what they say openly.',
  'Your first impression is useful data, not a final verdict.',
  'People are complicated; simple labels can hide important information.',
  'Watch what someone does when there is nothing obvious to gain.',
  'Your mood can colour your interpretation of someone else’s intentions.',
  'Patterns deserve more weight than promises made in emotional moments.',
  'Empathy becomes stronger when it includes curiosity about what you may be missing.',
  'People often repeat familiar roles until something interrupts the pattern.',
  'You can understand a motive without agreeing with the behaviour it produced.',
  'Fear can make people defend positions they would reconsider when calm.',
  'Pay attention to incentives, habits, and context before making a judgement.',
  'Your ego is capable of turning feedback into an attack if you let it.',
  'Not every reaction is about you.',
  'Self-awareness begins when you notice your own predictable triggers.',
  'People sometimes reveal priorities through what they consistently make time for.',
  'Emotional distance can make a confusing interaction easier to understand.',
  'Look for repeated contradictions instead of reacting to one strange moment.',
  'You are less likely to manipulate yourself when you name your own bias.',
  'Understanding others starts with admitting that your perspective is incomplete.',
  'When emotions rise, delay important conclusions if you can.',
  'Curiosity is a better detective than certainty.',
  'Your habits of interpretation can become as automatic as physical habits.',
  'People may defend an identity long after the original reason has disappeared.',
  'Good judgement combines observation with humility.',
  'Notice how status, fear, belonging, and incentives can shape behaviour.',
  'Your own patterns become easier to change once you can describe them honestly.',
  'Assumptions feel efficient, but careful observation often saves time later.',
  'Watch for the difference between what someone says they value and what they repeatedly choose.',
  'Understanding human behaviour is useful when it makes you wiser, not more cynical.',
  'You can recognise patterns without pretending you can predict every person.',
  'Human nature is complicated enough to require both empathy and boundaries.',
  'Know the objective before deciding what action deserves your energy.',
  'Preparation reduces the pressure to improvise badly.',
  'Choose the important battle rather than fighting every small inconvenience.',
  'Keep your long-term direction visible when short-term problems appear.',
  'Adapt your plan when the situation changes; strategy is not stubbornness.',
  'Know your own limits before committing your resources.',
  'Information can change the right move, so keep learning as you act.',
  'A calm retreat can preserve resources for a better opportunity later.',
  'Focus is a strategic advantage when distractions multiply.',
  'Break a large problem into smaller objectives you can actually execute.',
  'Your energy is a resource; do not spend it everywhere equally.',
  'Anticipate obstacles before they become emergencies.',
  'Leave room in your plan for unexpected events.',
  'Good strategy balances ambition with the resources you actually have.',
  'Use the environment to your advantage instead of fighting it unnecessarily.',
  'Clear priorities make decisions faster when pressure rises.',
  'Know what success looks like before you start measuring progress.',
  'If a plan repeatedly fails, change the plan rather than repeating the same move louder.',
  'Keep reserves of time and energy for problems you cannot predict.',
  'Separate the urgent from the important before committing your attention.',
  'Observation is part of action because it tells you what the situation is becoming.',
  'Choose timing carefully; the right move at the wrong moment can still fail.',
  'Good preparation creates flexibility rather than rigidity.',
  'Protect your strongest resources for the moments that matter most.',
  'When the path is blocked, search for another route before forcing the obstacle.',
  'Use small experiments to test a strategy before making a large commitment.',
  'Keep your emotions from deciding your strategy during high-pressure moments.',
  'Know when persistence is useful and when it has become wasted effort.',
  'Progress improves when each setback teaches the next adjustment.',
  'You do not need perfect information to make a disciplined next move.',
  'Build momentum by securing small wins that make the next step easier.',
  'A clear objective prevents busywork from pretending to be progress.',
  'Protect your attention from conflicts that do not serve your mission.',
  'Flexibility is strength when reality changes the conditions.',
  'Your strategy should serve the goal, not your attachment to the original plan.',
  'Choose a pace you can sustain when the project takes longer than expected.',
  'Good planning includes a response for when motivation disappears.',
  'Know which problems deserve immediate action and which can wait.',
  'Keep your next move simple enough to execute under pressure.',
  'Winning your own attention is often the first strategic victory.',
 ];

/** Deterministic day-of-year index into QUOTES, stable for the whole day. */
export function quoteForDate(date: Date = new Date()): string {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / 86_400_000);
  return QUOTES[dayOfYear % QUOTES.length];
}
