"use client";

import { useState } from "react";
import { useStore } from "@/lib/store";
import type { Activity, DayIndex, ActivityCategory } from "@/lib/types";
import { activitiesForDay } from "@/lib/logic";
import { DAY_LABELS, dayIndexOf, minutesOf } from "@/lib/date";
import { ActivityRow } from "../ActivityRow";
import { Card, Modal, Field, inputClass, Button, EmptyState } from "../ui";

function dateForDay(day: DayIndex): Date { const d = new Date(); d.setDate(d.getDate() + day - d.getDay()); return d; }
const CATEGORIES: { value: ActivityCategory; label: string }[] = [{ value: "wake", label: "Wake" }, { value: "meal", label: "Meal" }, { value: "study", label: "Study" }, { value: "research", label: "Research" }, { value: "coursework", label: "Coursework" }, { value: "gym", label: "Gym" }, { value: "college", label: "College" }, { value: "project", label: "Personal Project" }, { value: "prayer", label: "Prayer / Personal" }, { value: "prep", label: "Preparation" }, { value: "free", label: "Free time" }, { value: "other", label: "Other" }];
const emptyForm = { title: "", emoji: "📌", start: "09:00", end: "10:00", xp: "", category: "other" as ActivityCategory, days: [] as DayIndex[], topic: "", notes: "", findings: "" };

export function Schedule() {
  const { state, addActivity, updateActivity, deleteActivity } = useStore();
  const [selectedDay, setSelectedDay] = useState<DayIndex>(dayIndexOf()); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Activity | null>(null); const [form, setForm] = useState(emptyForm); const [error, setError] = useState(""); const [confirmDelete, setConfirmDelete] = useState<Activity | null>(null);
  const date = dateForDay(selectedDay); const acts = activitiesForDay(state, selectedDay); const totalXp = acts.reduce((s, a) => s + (a.xp || 0), 0); const categories = new Set(acts.map((a) => a.category)).size;
  const openAdd = () => { setEditing(null); setForm({ ...emptyForm, days: [selectedDay] }); setError(""); setOpen(true); };
  const openEdit = (a: Activity) => { setEditing(a); setForm({ title: a.title, emoji: a.emoji, start: a.start, end: a.end, xp: a.xp ? String(a.xp) : "", category: a.category, days: [...a.days], topic: a.topic ?? "", notes: a.notes ?? "", findings: a.findings ?? "" }); setError(""); setOpen(true); };
  const toggleDay = (d: DayIndex) => setForm((f) => ({ ...f, days: f.days.includes(d) ? f.days.filter((x) => x !== d) : [...f.days, d].sort((a, b) => a - b) }));
  const save = () => { if (!form.title.trim()) return setError("Please enter a title."); if (!form.days.length) return setError("Select at least one day."); if (minutesOf(form.end) < minutesOf(form.start)) return setError("End time must be after start time."); const xp = form.xp.trim() === "" ? 0 : parseInt(form.xp, 10); if (Number.isNaN(xp) || xp < 0) return setError("XP must be a non-negative number."); const payload = { title: form.title.trim(), emoji: form.emoji || "📌", start: form.start, end: form.end, xp, category: form.category, days: form.days, ...(form.category === "research" ? { topic: form.topic.trim() || undefined, notes: form.notes.trim() || undefined, findings: form.findings.trim() || undefined } : {}) }; if (editing) updateActivity({ ...payload, id: editing.id }); else addActivity(payload); setOpen(false); };

  return <div className="space-y-4 pb-4">
    <header className="norou-page-head pt-1"><div><div className="norou-eyebrow">NOVA PLAN</div><h1>Plan</h1><p>Shape your day, then let Nova help you execute it.</p></div><button className="norou-money-add" onClick={openAdd}>+ Block</button></header>
    <div className="norou-plan-days">{DAY_LABELS.map((label, i) => { const d = i as DayIndex; const active = selectedDay === d; return <button key={label} onClick={() => setSelectedDay(d)} className={active ? "active" : ""}><span>{label}</span>{dayIndexOf() === d && <small>today</small>}</button>; })}</div>
    <Card className="norou-plan-hero p-5"><div className="flex items-end justify-between gap-4"><div><div className="norou-eyebrow">{selectedDay === dayIndexOf() ? "TODAY" : DAY_LABELS[selectedDay]}</div><strong className="norou-plan-number">{acts.length}</strong><span className="text-sm text-neutral-500 ml-2">blocks planned</span><p className="text-xs text-neutral-600 mt-2">{totalXp} XP across {categories || 0} focus areas.</p></div><div className="norou-plan-orb">◫</div></div><div className="mt-5 flex gap-2"><button className="norou-small-action" onClick={openAdd}>Add block</button><button className="norou-small-action" onClick={() => setSelectedDay(dayIndexOf())}>Jump to today</button></div></Card>
    <section><div className="flex items-center justify-between mb-3"><div><div className="norou-eyebrow">TIMELINE</div><h2 className="text-lg font-black text-white mt-1">Your day</h2></div><span className="text-[9px] font-bold text-neutral-600">{new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(date)}</span></div>{acts.length === 0 ? <Card><EmptyState icon="◫" text="No blocks planned for this day" /></Card> : <div className="space-y-2">{acts.map((a) => <ActivityRow key={a.id} activity={a} date={date} showActions onEdit={openEdit} onDelete={(x) => setConfirmDelete(x)} />)}</div>}</section>
    <Card className="p-4"><div className="norou-eyebrow">PLANNING TIP</div><p className="text-sm text-neutral-300 mt-2 leading-6">Keep the next block clear and realistic. Nova can handle the details when you open the command centre.</p></Card>
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? "Edit block" : "Add block"}><div className="grid grid-cols-[64px_1fr] gap-3"><Field label="Icon"><input className={`${inputClass} text-center`} value={form.emoji} onChange={(e) => setForm({ ...form, emoji: e.target.value })} maxLength={4} /></Field><Field label="Title"><input className={inputClass} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Start"><input type="time" className={inputClass} value={form.start} onChange={(e) => setForm({ ...form, start: e.target.value })} /></Field><Field label="End"><input type="time" className={inputClass} value={form.end} onChange={(e) => setForm({ ...form, end: e.target.value })} /></Field></div><div className="grid grid-cols-2 gap-3"><Field label="XP"><input type="number" className={inputClass} value={form.xp} onChange={(e) => setForm({ ...form, xp: e.target.value })} /><span /></Field><Field label="Category"><select className={inputClass} value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as ActivityCategory })}>{CATEGORIES.map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}</select></Field></div><Field label="Days"><div className="flex gap-1.5">{DAY_LABELS.map((label, i) => { const d = i as DayIndex; return <button key={label} type="button" onClick={() => toggleDay(d)} className={`flex-1 rounded-lg py-2 text-[11px] font-bold ${form.days.includes(d) ? "bg-[#a855f7] text-white" : "bg-[#2a2a2a] text-neutral-400"}`}>{label[0]}</button>; })}</div></Field>{form.category === "research" && <div className="rounded-xl bg-[#a855f7]/5 border border-[#a855f7]/20 p-3"><Field label="Topic"><input className={inputClass} value={form.topic} onChange={(e) => setForm({ ...form, topic: e.target.value })} /></Field><Field label="Notes"><textarea className={`${inputClass} min-h-16`} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></Field><Field label="Key findings"><textarea className={`${inputClass} min-h-16`} value={form.findings} onChange={(e) => setForm({ ...form, findings: e.target.value })} /></Field></div>}{error && <p className="text-xs text-red-400">{error}</p>}<div className="flex gap-2 mt-2"><Button variant="ghost" className="flex-1" onClick={() => setOpen(false)}>Cancel</Button><Button className="flex-1" onClick={save}>{editing ? "Save" : "Add"}</Button></div></Modal>
    <Modal open={confirmDelete !== null} onClose={() => setConfirmDelete(null)} title="Delete block?"><p className="text-sm text-neutral-300 mb-4">Delete <span className="font-semibold text-white">{confirmDelete?.title}</span>?</p><div className="flex gap-2"><Button variant="ghost" className="flex-1" onClick={() => setConfirmDelete(null)}>Cancel</Button><Button variant="danger" className="flex-1" onClick={() => { if (confirmDelete) deleteActivity(confirmDelete.id); setConfirmDelete(null); }}>Delete</Button></div></Modal>
  </div>;
}
